import React, { useState, useEffect } from 'react';
import TopNavigation from './TopNavigation';
import { RepoData } from './VideoRepoOverview';
import AlertDialog from './AlertDialog';

interface RepoFilesViewProps {
    onNavigate: (view: 'dashboard' | 'repo' | 'timeline' | 'diff' | 'assets' | 'settings' | 'create-repo' | 'repo-files') => void;
    repoData?: RepoData | null;
}

interface FileNode {
    id: string;
    name: string;
    type: 'folder' | 'file';
    content?: string;
    children?: FileNode[];
    isOpen?: boolean;
}

const RepoFilesView: React.FC<RepoFilesViewProps> = ({ onNavigate, repoData }) => {
    const [files, setFiles] = useState<FileNode[]>([]);
    const [selectedFile, setSelectedFile] = useState<FileNode | null>(null);
    const [editorContent, setEditorContent] = useState('');
    const [isDirty, setIsDirty] = useState(false);
    const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);

    // Initialize files from repoData
    useEffect(() => {
        if (!repoData) return;

        // Mock file system generation similar to Overview but with content
        const initialFiles: FileNode[] = [
            {
                id: 'config',
                name: 'trem.json',
                type: 'file',
                content: JSON.stringify({
                    name: repoData.name,
                    brief: repoData.brief,
                    created: new Date().toISOString(),
                    version: "1.0.0"
                }, null, 2)
            },
            {
                id: 'media',
                name: 'media',
                type: 'folder',
                isOpen: true,
                children: [
                    {
                        id: 'raw', name: 'raw_footage', type: 'folder', isOpen: false, children: repoData.assets?.map((a: any) => ({
                            id: a.id,
                            name: a.name || a.id,
                            type: 'file',
                            content: `[Binary File: ${a.name}]\nSize: 450MB\nFormat: MP4\nCodec: h.264`
                        })) || []
                    }
                ]
            },
            {
                id: 'meta',
                name: 'meta',
                type: 'folder',
                isOpen: true,
                children: repoData.assets?.map((a: any) => ({
                    id: `meta_${a.id}`,
                    name: `${a.id}.json`,
                    type: 'file',
                    content: JSON.stringify({
                        asset_id: a.id,
                        duration_frames: Math.floor(Math.random() * 1000),
                        scenes: [
                            { scene_id: 1, start_frame: 0, end_frame: 120, label: "Intro" },
                            { scene_id: 2, start_frame: 121, end_frame: 450, label: "Action" }
                        ]
                    }, null, 2)
                })) || []
            },
            {
                id: 'lock',
                name: 'trem.lock',
                type: 'file',
                content: `# Trem Lock File\n# Generated by Trem-AI\nhash_algorithm=sha256\n\n[assets]\n${repoData.assets?.map((a: any) => `${a.id}=sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`).join('\n')}`
            }
        ];
        setFiles(initialFiles);
    }, [repoData]);

    const toggleFolder = (nodeId: string, nodes: FileNode[]): FileNode[] => {
        return nodes.map(node => {
            if (node.id === nodeId) {
                return { ...node, isOpen: !node.isOpen };
            }
            if (node.children) {
                return { ...node, children: toggleFolder(nodeId, node.children) };
            }
            return node;
        });
    };

    const findFile = (nodeId: string, nodes: FileNode[]): FileNode | null => {
        for (const node of nodes) {
            if (node.id === nodeId) return node;
            if (node.children) {
                const found = findFile(nodeId, node.children);
                if (found) return found;
            }
        }
        return null;
    };

    const updateFileContent = (nodeId: string, newContent: string, nodes: FileNode[]): FileNode[] => {
        return nodes.map(node => {
            if (node.id === nodeId) {
                return { ...node, content: newContent };
            }
            if (node.children) {
                return { ...node, children: updateFileContent(nodeId, newContent, node.children) };
            }
            return node;
        });
    };

    const deleteFile = (nodeId: string, nodes: FileNode[]): FileNode[] => {
        return nodes.filter(node => node.id !== nodeId).map(node => {
            if (node.children) {
                return { ...node, children: deleteFile(nodeId, node.children) };
            }
            return node;
        });
    };

    const handleFileClick = (node: FileNode) => {
        if (node.type === 'folder') {
            setFiles(toggleFolder(node.id, files));
        } else {
            if (isDirty) {
                if (!window.confirm("You have unsaved changes. Discard them?")) return;
            }
            setSelectedFile(node);
            setEditorContent(node.content || '');
            setIsDirty(false);
        }
    };

    const handleSave = () => {
        if (selectedFile) {
            setFiles(updateFileContent(selectedFile.id, editorContent, files));
            setIsDirty(false);
        }
    };

    const handleDeleteClick = () => {
        if (selectedFile) {
            setDeleteDialogOpen(true);
        }
    };

    const confirmDelete = () => {
        if (selectedFile) {
            setFiles(deleteFile(selectedFile.id, files));
            setSelectedFile(null);
            setEditorContent('');
            setIsDirty(false);
            setDeleteDialogOpen(false);
        }
    };

    // Recursive tree renderer
    const renderTree = (nodes: FileNode[], depth = 0) => {
        return nodes.map(node => (
            <div key={node.id}>
                <div
                    className={`flex items-center gap-2 py-1 px-2 cursor-pointer text-sm font-mono border-l-2 hover:bg-slate-100 dark:hover:bg-white/5 transition-colors ${selectedFile?.id === node.id ? 'bg-primary/10 border-primary text-slate-900 dark:text-white font-bold' : 'border-transparent text-slate-600 dark:text-slate-400'}`}
                    style={{ paddingLeft: `${depth * 12 + 8}px` }}
                    onClick={() => handleFileClick(node)}
                >
                    <span className={`material-icons-outlined text-base ${node.type === 'folder' ? 'text-amber-400' : 'text-slate-400'}`}>
                        {node.type === 'folder' ? (node.isOpen ? 'folder_open' : 'folder') : 'description'}
                    </span>
                    <span className="truncate">{node.name}</span>
                </div>
                {node.type === 'folder' && node.isOpen && node.children && (
                    <div>{renderTree(node.children, depth + 1)}</div>
                )}
            </div>
        ));
    };

    const [isMobileSidebarOpen, setIsMobileSidebarOpen] = useState(false);

    // ... (rest of logic)

    return (
        <div className="flex flex-col h-full bg-slate-50 dark:bg-black text-slate-900 dark:text-white font-sans transition-colors duration-300">
            <TopNavigation onNavigate={onNavigate} />

            {/* Toolbar */}
            <div className="px-4 md:px-6 py-3 border-b border-slate-200 dark:border-white/10 flex flex-col md:flex-row items-center justify-between bg-white dark:bg-black/40 gap-3 md:gap-0">
                <div className="w-full md:w-auto flex items-center justify-between md:justify-start gap-4">
                    <div className="flex items-center gap-4">
                        <button
                            onClick={() => setIsMobileSidebarOpen(!isMobileSidebarOpen)}
                            className="md:hidden text-slate-500 dark:text-slate-400"
                        >
                            <span className="material-icons-outlined">{isMobileSidebarOpen ? 'menu_open' : 'menu'}</span>
                        </button>

                        <button onClick={() => onNavigate('repo')} className="flex items-center gap-2 text-slate-500 hover:text-slate-900 dark:text-slate-400 dark:hover:text-white transition-colors">
                            <span className="material-icons-outlined">arrow_back</span>
                            <span className="text-sm font-mono uppercase tracking-wider hidden sm:inline">Back to Overview</span>
                            <span className="text-sm font-mono uppercase tracking-wider sm:hidden">Back</span>
                        </button>
                    </div>

                    <div className="h-6 w-px bg-slate-200 dark:bg-white/10 hidden md:block"></div>
                    <h2 className="text-lg font-display font-bold truncate">File Manager</h2>
                </div>
                <div className="w-full md:w-auto flex items-center justify-end gap-2">
                    <button
                        onClick={handleDeleteClick}
                        disabled={!selectedFile}
                        className="px-3 py-1.5 rounded-md border border-red-200 dark:border-red-900/30 text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20 disabled:opacity-50 disabled:cursor-not-allowed transition-colors text-sm flex items-center gap-2"
                    >
                        <span className="material-icons-outlined text-sm">delete</span>
                        <span className="hidden sm:inline">Delete</span>
                    </button>
                    <button
                        onClick={handleSave}
                        disabled={!isDirty}
                        className="px-3 py-1.5 rounded-md bg-primary hover:bg-primary_hover text-white disabled:opacity-50 disabled:cursor-not-allowed transition-colors text-sm font-medium flex items-center gap-2 shadow-sm"
                    >
                        <span className="material-icons-outlined text-sm">save</span>
                        <span className="hidden sm:inline">Save Changes</span>
                    </button>
                </div>
            </div>

            <div className="flex-1 flex overflow-hidden relative">
                {/* Sidebar Tree */}
                <div className={`w-64 border-r border-slate-200 dark:border-white/10 bg-slate-50 dark:bg-black/20 overflow-y-auto p-2 absolute md:relative top-0 bottom-0 left-0 z-20 transition-transform duration-300 transform ${isMobileSidebarOpen ? 'translate-x-0 bg-white dark:bg-zinc-900 shadow-xl' : '-translate-x-full md:translate-x-0'}`}>
                    {renderTree(files)}
                </div>

                {/* Overlay for mobile sidebar */}
                {isMobileSidebarOpen && (
                    <div
                        className="fixed inset-0 bg-black/50 z-10 md:hidden"
                        onClick={() => setIsMobileSidebarOpen(false)}
                    ></div>
                )}

                {/* Editor / Preview Area */}
                <div className="flex-1 flex flex-col bg-white dark:bg-[#1e1e1e] min-w-0">
                    {selectedFile ? (
                        <>
                            <div className="px-4 py-2 bg-slate-100 dark:bg-[#252526] border-b border-slate-200 dark:border-white/5 text-xs font-mono text-slate-500 dark:text-slate-400 flex justify-between">
                                <span>{selectedFile.name}</span>
                                <span className="uppercase">{selectedFile.name.split('.').pop() || 'TXT'}</span>
                            </div>

                            {/* Content Renderer */}
                            <div className="flex-1 overflow-hidden relative">
                                {['mp4', 'mov', 'webm'].some(ext => selectedFile.name.toLowerCase().endsWith(ext)) ? (
                                    <div className="w-full h-full flex items-center justify-center bg-black">
                                        {/* In a real app, src would be a blob URL or server path. For mock, we show a placeholder player */}
                                        <div className="text-center text-white/50">
                                            <span className="material-icons-outlined text-6xl">play_circle_outline</span>
                                            <p className="mt-4 font-mono text-sm">Preview: {selectedFile.name}</p>
                                            <p className="text-xs opacity-50">(Media playback simulation)</p>
                                        </div>
                                    </div>
                                ) : ['jpg', 'jpeg', 'png', 'gif', 'webp'].some(ext => selectedFile.name.toLowerCase().endsWith(ext)) ? (
                                    <div className="w-full h-full flex items-center justify-center bg-black/90 p-8">
                                        <div className="text-center text-white/50">
                                            <span className="material-icons-outlined text-6xl">image</span>
                                            <p className="mt-4 font-mono text-sm">Image Preview: {selectedFile.name}</p>
                                        </div>
                                    </div>
                                ) : ['mp3', 'wav', 'aac'].some(ext => selectedFile.name.toLowerCase().endsWith(ext)) ? (
                                    <div className="w-full h-full flex flex-col items-center justify-center bg-slate-900 text-white">
                                        <span className="material-icons-outlined text-6xl mb-4 text-primary animate-pulse">graphic_eq</span>
                                        <p className="font-mono">{selectedFile.name}</p>
                                        <div className="w-64 h-1 bg-slate-700 mt-6 rounded-full overflow-hidden">
                                            <div className="h-full bg-primary w-1/3"></div>
                                        </div>
                                    </div>
                                ) : (
                                    <textarea
                                        value={editorContent}
                                        onChange={(e) => {
                                            setEditorContent(e.target.value);
                                            setIsDirty(true);
                                        }}
                                        className="w-full h-full p-4 bg-transparent outline-none font-mono text-sm resize-none text-slate-800 dark:text-[#d4d4d4] leading-relaxed"
                                        spellCheck={false}
                                    />
                                )}
                            </div>
                        </>
                    ) : (
                        <div className="flex-1 flex flex-col items-center justify-center text-slate-300 dark:text-slate-600">
                            <span className="material-icons-outlined text-6xl mb-4">description</span>
                            <p className="font-mono text-sm">Select a file to view or edit content</p>
                        </div>
                    )}
                </div>
            </div>

            {/* Status Bar */}
            <div className="h-6 bg-primary text-white px-4 flex items-center justify-between text-[10px] font-mono select-none">
                <span>{selectedFile ? `Editing: ${selectedFile.name}` : 'Ready'}</span>
                <span>{repoData?.name ? `Repo: ${repoData.name}` : 'No Repo Loaded'}</span>
            </div>

            {/* Delete Confirmation Dialog */}
            <AlertDialog
                isOpen={deleteDialogOpen}
                title="Confirm Selection Deletion"
                description={
                    <span>
                        Are you sure you want to delete <strong className="text-slate-900 dark:text-white">{selectedFile?.name}</strong>?
                        <br /><span className="text-xs mt-1 block">This action cannot be undone.</span>
                    </span>
                }
                confirmText="Delete File"
                cancelText="Cancel"
                type="danger"
                onConfirm={confirmDelete}
                onCancel={() => setDeleteDialogOpen(false)}
            />
        </div>
    );
};

export default RepoFilesView;
